### ISSUE TITLE
reporting alarms, IR-status

### ISSUE THREAD

**Issue by tobiasoort** [StuffNL/domoticz-woonveilig#2]
Hi,

The latest version added all my IR sensors to Domoticz, and arming/disarming the panel from domoticz (and from the panel itself, which is then seen by domoticz) works great.

I wonder though how I should get an alarm reported back. The IR sensors have never given me an 'on' or 'active' state in Domoticz - not even when the system was armed. I also see no way to have domoticz notice and/or handle an alarm state.

Am I missing something? Is there a stub somewhere in your code I can expand to add this functionality?

**Comment by svdbeemt** [comment]
Hi @tobiasoort, 

- In order to use Domoticz alarm state you have to connect the WoonVeilg alarmsystem with the Domoticz SecurityPanel. I've created a LUA script which you can find on: https://github.com/StuffNL/domoticz-woonveilig

- Currently there is a problem with the IR sensors in the plugin. The won't detect a security breach. The doorlock sensors are working fine.

**Comment by tobiasoort** [comment]
That Lua script seems to only provide linking to the 'alarm panel' UI in Domoticz. There is no code there that signals Domoticz that a burglary is in progress. Unless I'm missing something.

I'll see what I can find out regarding the IR sensors.

**Comment by imdos** [comment]
Hi @tobiasoort,

You could define some logic for yourself within Domoticz and/or you can catch all relevant data through another channel. 

Therefore I can recommend the great work done by [Bjorn van den Brule](http://brule.nl/project-woonveilig4.php). I have modified his script, [which can be found here](https://github.com/imdos/woonveilig/blob/master/woonveilig-service-v7.php), a bit more to my needs and added the following:

- pid file and checking thereof (check if running and don't allow duplicate startup)
- logging to [Slack](https://www.slack.com)
- logging to Domoticz

**Comment by tobiasoort** [comment]
Thanks for the link! I'll see if I can roll something from that :)
